const jwt = require('jsonwebtoken');
const db = require('../models');
const User = db.User;

exports.protect = async (req, res, next) => {
  let token;

  // 1. Grab the token from the HTTP Authorization Header
  if (req.headers.authorization && req.headers.authorization.startsWith('Bearer')) {
    try {
      token = req.headers.authorization.split(' ')[1];
      
      // 2. Decode the session token generated by your authController
      const decoded = jwt.verify(token, process.env.JWT_SECRET || 'your_jwt_secret');
      
      // 3. Find the user in Supabase and attach their details to the request object
      req.user = await User.findByPk(decoded.id);
      
      if (!req.user) {
        return res.status(401).json({ message: 'User profile mismatch. Not authorized.' });
      }

      next(); // Hand control over to the route or next middleware
    } catch (error) {
      console.error('Token Verification Error:', error);
      return res.status(401).json({ message: 'Not authorized, token failed' });
    }
  }

  if (!token) {
    return res.status(401).json({ message: 'Not authorized, no token provided' });
  }
};