begin;

create extension if not exists pgcrypto;

do $$
begin
  if not exists (
    select 1
    from pg_type
    where typname = 'enum_users_role'
  ) then
    create type public.enum_users_role as enum ('student', 'alumni', 'admin');
  end if;
end
$$;

create table if not exists public."Users" (
  id integer generated by default as identity primary key,
  name varchar(255) not null,
  email varchar(255) not null unique,
  "passwordHash" varchar(255) not null,
  role public.enum_users_role not null,
  "yearOfStudy" integer,
  branch varchar(255),
  company varchar(255),
  "professionalRole" varchar(255),
  interests jsonb not null default '[]'::jsonb,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."Communities" (
  id integer generated by default as identity primary key,
  name varchar(255) not null,
  description text not null,
  category varchar(255) not null,
  "createdBy" integer not null references public."Users"(id) on update cascade on delete cascade,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."Memberships" (
  "communityId" integer not null references public."Communities"(id) on update cascade on delete cascade,
  "userId" integer not null references public."Users"(id) on update cascade on delete cascade,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  primary key ("communityId", "userId")
);

create table if not exists public."Threads" (
  id integer generated by default as identity primary key,
  "communityId" integer not null references public."Communities"(id) on update cascade on delete cascade,
  title varchar(255) not null,
  body text not null,
  "authorId" integer not null references public."Users"(id) on update cascade on delete cascade,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."Replies" (
  id integer generated by default as identity primary key,
  "threadId" integer not null references public."Threads"(id) on update cascade on delete cascade,
  body text not null,
  "authorId" integer not null references public."Users"(id) on update cascade on delete cascade,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."Events" (
  id integer generated by default as identity primary key,
  title varchar(255) not null,
  description text not null,
  date timestamptz not null,
  location varchar(255) not null,
  type varchar(255) not null,
  "organizerId" integer not null references public."Users"(id) on update cascade on delete cascade,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."Jobs" (
  id integer generated by default as identity primary key,
  title varchar(255) not null,
  company varchar(255) not null,
  description text not null,
  location varchar(255),
  type varchar(255) not null,
  deadline timestamptz,
  "contactEmail" varchar(255) not null,
  "createdBy" integer not null references public."Users"(id) on update cascade on delete cascade,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint jobs_contact_email_chk check ("contactEmail" ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')
);

create index if not exists communities_created_by_idx on public."Communities" ("createdBy");
create index if not exists memberships_user_id_idx on public."Memberships" ("userId");
create index if not exists threads_community_id_idx on public."Threads" ("communityId");
create index if not exists threads_author_id_idx on public."Threads" ("authorId");
create index if not exists replies_thread_id_idx on public."Replies" ("threadId");
create index if not exists replies_author_id_idx on public."Replies" ("authorId");
create index if not exists events_date_idx on public."Events" (date);
create index if not exists events_organizer_id_idx on public."Events" ("organizerId");
create index if not exists jobs_created_by_idx on public."Jobs" ("createdBy");
create index if not exists jobs_deadline_idx on public."Jobs" (deadline);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$;

drop trigger if exists set_users_updated_at on public."Users";
create trigger set_users_updated_at
before update on public."Users"
for each row
execute function public.set_updated_at();

drop trigger if exists set_communities_updated_at on public."Communities";
create trigger set_communities_updated_at
before update on public."Communities"
for each row
execute function public.set_updated_at();

drop trigger if exists set_memberships_updated_at on public."Memberships";
create trigger set_memberships_updated_at
before update on public."Memberships"
for each row
execute function public.set_updated_at();

drop trigger if exists set_threads_updated_at on public."Threads";
create trigger set_threads_updated_at
before update on public."Threads"
for each row
execute function public.set_updated_at();

drop trigger if exists set_replies_updated_at on public."Replies";
create trigger set_replies_updated_at
before update on public."Replies"
for each row
execute function public.set_updated_at();

drop trigger if exists set_events_updated_at on public."Events";
create trigger set_events_updated_at
before update on public."Events"
for each row
execute function public.set_updated_at();

drop trigger if exists set_jobs_updated_at on public."Jobs";
create trigger set_jobs_updated_at
before update on public."Jobs"
for each row
execute function public.set_updated_at();

commit;
